#!/bin/bash

echo $PACKAGE_INSTALLATION_ENV
set | grep PACKAGE_INSTALLATION_ENV

echo "PACKAGE_INSTALLATION_ENV: $PACKAGE_INSTALLATION_ENV"
echo "Checking sdk mode..."
# If PACKAGE_INSTALLATION_ENV is github, update sdk mode to dist
if [ "$PACKAGE_INSTALLATION_ENV" = "github" ]; then
  echo "Updating sdk mode to dist..."
  node ./scripts/swap-mode.js
else
  echo "PACKAGE_INSTALLATION_ENV is not github, local installation, changing to use the src..."
  node ./scripts/local-run.js
fi

if exists yarn; then
  # Run yarn commands
  (cd ../../ && yarn --frozen-lockfile --prefer-offline && yarn build && cd -) || exit 1
else
  (cd ../../ && npm install && npm run build && cd -) || exit 1
fi

exit 0
