source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
# Floor is set by the locked gems, currently connection_pool 3.0.2 (>= 3.2.0).
ruby ">= 3.2.0"

# Exclude problematic versions of cocoapods and activesupport that causes build failures.
gem 'cocoapods', '>= 1.13', '!= 1.15.0', '!= 1.15.1'
gem 'activesupport', '>= 6.1.7.5', '!= 7.1.0'
gem 'xcodeproj', '< 1.26.0'
gem 'concurrent-ruby', '>= 1.3.7' # >= 1.3.7 fixes CVE-2026-54904 (AtomicReference#update NaN livelock DoS)
gem 'json', '>= 2.19.9' # >= 2.19.9 fixes CVE-2026-54696 (generator heap overflow when streaming to an IO)
