const LINK_EVENT_TYPE_KEYS = [
    'integrationConnected',
    'integrationConnectionError',
    'transferCompleted',
    'integrationSelected',
    'credentialsEntered',
    'transferStarted',
    'transferPreviewed',
    'transferPreviewError',
    'transferExecutionError',
    'transferExecuted',
    'transferInitiated',
    'transferNoEligibleAssets',
    'pageLoaded',
    'walletMessageSigned',
    'verifyDonePage',
    'verifyWalletRejected',
    'integrationMfaRequired',
    'integrationMfaEntered',
    'integrationOAuthStarted',
    'integrationAccountSelectionRequired',
    'transferAssetSelected',
    'transferNetworkSelected',
    'transferAmountEntered',
    'transferMfaRequired',
    'transferMfaEntered',
    'transferKycRequired',
    'connectionDeclined',
    'transferConfigureError',
    'connectionUnavailable',
    'transferDeclined',
    'legalTermsViewed',
    'seeWhatHappenedClicked',
    'executeFundingStep',
    'fundingOptionsUpdated',
    'fundingOptionsViewed',
    'gasIncreaseWarning',
    'linkTransferQRGenerated',
    'methodSelected',
    'homePageLoaded',
    'defiWalletError',
];
export const mappedLinkEvents = {
    brokerageAccountAccessToken: 'integrationConnected',
    delayedAuthentication: 'integrationConnected',
    transferFinished: 'transferCompleted',
    loaded: 'pageLoaded',
};
export function isLinkEventTypeKey(key) {
    return LINK_EVENT_TYPE_KEYS.includes(key);
}
