export const DARK_THEME_COLOR_TOP = '#1E1E24';
export const LIGHT_THEME_COLOR_TOP = '#F3F4F5';
export const DARK_THEME_COLOR_BOTTOM = '#0E0D0D';
export const LIGHT_THEME_COLOR_BOTTOM = '#FBFBFB';

export const WHITELISTED_ORIGINS = [
  '*.meshconnect.com',
  '*.getfront.com',
  '*.walletconnect.com',
  '*.walletconnect.org',
  '*.walletlink.org',
  '*.coinbase.com',
  '*.okx.com',
  '*.gemini.com',
  '*.coinbase.com',
  '*.hcaptcha.com',
  '*.robinhood.com',
  '*.google.com',
  'https://meshconnect.com',
  'https://getfront.com',
  'https://walletconnect.com',
  'https://walletconnect.org',
  'https://walletlink.org',
  'https://coinbase.com',
  'https://okx.com',
  'https://gemini.com',
  'https://coinbase.com',
  'https://hcaptcha.com',
  'https://robinhood.com',
  'https://google.com',
  'https://front-web-platform-dev',
  'https://front-b2b-api-test.azurewebsites.net',
  'https://applink.robinhood.com',
  'https://bonfire.robinhood.com',
  'https://api.stripe.com',
  'https://js.stripe.com',
  'https://m.stripe.network',
  'https://bonfire.robinhood.com',
  'https://crumbs.robinhood.com',
  'https://fp.robinhood.com',
  'https://nummus.robinhood.com',
  'https://cdn.robinhood.com',
  'https://fp.robinhood.com',
  'https://robinhood-api.arkoselabs.com',
  'https://app.usercentrics.eu',
  'https://link.trustwallet.com',
];
