name: RNSDK build iOS example app

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - feature/SCS-268-build-ios

defaults:
  run:
    shell: bash

env:
  PACKAGE_INSTALLATION_ENV: 'github'
  NODE_VERSION: '18'
  NODE_OPTIONS: '--max_old_space_size=4096'
  RUBY_VERSION: '3.0'
  # XCODE_VERSION: '15'
  WORKING_DIRECTORY: examples/react-native-example

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 20
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set image version  🔂
        run: echo "ImageVersion=$ImageVersion" >> $GITHUB_ENV
      # - name: Select Xcode 📱
      #   run: sudo xcode-select --switch /Applications/Xcode_${{ env.XCODE_VERSION }}.app
      - name: Node 📚
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Node cache ☊
        uses: actions/cache@v2.1.6
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-${{ env.ImageVersion }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.ImageVersion }}-node-
      - name: Install node modules 📦
        run: yarn install --frozen-lockfile
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: CocoaPods cache 🧳
        uses: actions/cache@v2.1.4
        with:
          path: ${{ env.WORKING_DIRECTORY }}/ios/vendor/bundle
          key: ${{ runner.os }}-${{ env.ImageVersion }}-gems-${{ hashFiles('ios/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.ImageVersion }}-gems

      - name: Install/Check CocoaPods
        working-directory: ${{ env.WORKING_DIRECTORY }}/ios
        run: pod --version
      #   run: |
      #     bundle config path vendor/bundle
      #     bundle config deployment true
      #     bundle install

      - name: Pods cache 🏫
        uses: actions/cache@v2.1.6
        with:
          path: ${{ env.WORKING_DIRECTORY }}/ios/Pods
          key: ${{ runner.os }}-${{ env.ImageVersion }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.ImageVersion }}-pods-

      - name: Install Pods and update lock 🔏
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npx pod-install

      - name: Build iOS App for Firebase 🏗️
        uses: yukiarrr/ios-build-action@v1.11.0
        with:
          project-path: ${{ env.WORKING_DIRECTORY }}/ios/MeshConnectRNSDK.xcodeproj
          p12-base64: ${{ secrets.IOS_P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.IOS_MOBILE_PROVISION_BASE64 }}
          code-signing-identity: 'iPhone Distribution'
          team-id: ${{ secrets.IOS_TEAM_ID }}
          certificate-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          workspace-path: ${{ env.WORKING_DIRECTORY }}/ios/MeshConnectRNSDK.xcworkspace
          output-path: ${{ env.WORKING_DIRECTORY }}/ios/build/output.ipa
          scheme: MeshConnectRNSDK

      - name: Upload iOS App to Firebase App Distribution 🏁
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_IOS_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIAL_FILE_CONTENT }}
          groups: testers
          releaseNotes: ${{ github.event.pull_request.title || github.ref_name }}\n${{ github.event.head_commit.message }}
          file: ${{ env.WORKING_DIRECTORY }}ios/build/output.ipa
