name: 'React Native Readme.io Release Notes'
on:
  release:
    types:
      - published

jobs:
  sync-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: "Build Changelog"
        uses: mikepenz/release-changelog-builder-action@{latest-release}
        with:
          configurationJson: |
            {
              "categories": [
                {
                  "title": "## 🚀 Features",
                  "labels": ["feature"]
                },
                {
                  "title": "## 🐛 Fixes",
                  "labels": ["fix"]
                },
                {
                  "key": "tests",
                  "title": "## 🧪 Tests",
                  "labels": ["test"]
                },
                {
                  "title": "## 🧪 Tests and some 🪄 Magic",
                  "labels": ["test", "magic"],
                  "exclude_labels": ["no-magic"],
                  "exhaustive": true,
                  "exhaustive_rules": "false",
                  "empty_content": "- no matching PRs",
                  "rules": [
                    {
                      "pattern": "open",
                      "on_property": "status",
                      "flags": "gu"
                    }
                  ]
                }
              ],
              "ignore_labels": [
                "ignore"
              ],
              "sort": {
                "order": "ASC",
                "on_property": "mergedAt"
              },
              "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
              "pr_template": "- #{{TITLE}}\n   - PR: ##{{NUMBER}}",
              "empty_template": "- no changes",
              "label_extractor": [
                {
                  "pattern": "(.) (.+)",
                  "target": "$1",
                  "flags": "gu"
                },
                {
                  "pattern": "\\[Issue\\]",
                  "on_property": "title",
                  "method": "match"
                }
              ],
              "duplicate_filter": {
                "pattern": "\\[ABC-....\\]",
                "on_property": "title",
                "method": "match"
              },
              "reference": {
                "pattern": ".*\\ \\#(.).*",
                "on_property": "body",
                "method": "replace",
                "target": "$1"
              },
              "transformers": [
                {
                  "pattern": "[\\-\\*] (\\[(...|TEST|CI|SKIP)\\])( )?(.+?)\n(.+?[\\-\\*] )(.+)",
                  "target": "- $4\n  - $6"
                }
              ],
              "trim_values": false,
              "max_tags_to_fetch": 200,
              "max_pull_requests": 200,
              "max_back_track_time_days": 365,
              "exclude_merge_branches": [
                "Owner/qa"
              ],
              "tag_resolver": {
                "method": "semver",
                "filter": {
                  "pattern": "api-(.+)",
                  "flags": "gu"
                }
              },
              "base_branches": [
                "dev"
              ]
          }
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: "Synchronize release notes"
        run: |
          API_KEY=${{ secrets.README_IO_API_KEY }}
          DOCUMENTATION_ID=${{ secrets.README_IO_DOCUMENTATION_ID }}
          
          curl -X POST "https://api.readme.io/v1/docs/$DOCUMENTATION_ID" \
            -H "Content-Type: application/json" \
            -H "Authorization: $API_KEY" \
            -d "{\"body\": \"${{steps.github_release.outputs.changelog}}\"}"
